version: "3.9"

volumes:
  static:

services:

  auth-microservice:
    build: ./auth-microservice/
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    
    volumes:
      - static:/var/www/static
      
  course-microservice:
    build: ./course-microservice/
    command: gunicorn config.wsgi --bind 0.0.0.0:8001
    volumes:
      - static:/var/www/static
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/www/static
    ports:
      - 4000:80
    depends_on:
      - auth-microservice
